# Generated by Django 2.2.14 on 2020-11-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201110_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='roles', to='rbac.Role', verbose_name='拥有的所有角色'),
        ),
    ]
