# Generated by Django 2.2.14 on 2020-11-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201110_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='rbac.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='roles', to='rbac.Role', verbose_name='拥有的所有角色'),
        ),
    ]
