# Generated by Django 2.2.14 on 2020-11-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0006_auto_20201110_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='ammic_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ammic_group', to='rbac.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ammic_role',
            field=models.ManyToManyField(related_name='ammic_role', to='rbac.Role', verbose_name='拥有的所有角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '邮箱已经在系统中存在'}, max_length=100, unique=True, verbose_name='邮箱'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(error_messages={'unique': '姓名已经在系统中存在'}, max_length=30, null=True, unique=True, verbose_name='姓名'),
        ),
    ]
