# Generated by Django 2.2.14 on 2020-12-30 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201111_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='配置类型')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='配置图片')),
                ('title', models.CharField(max_length=64, verbose_name='配置标题')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='配置描述')),
                ('router', models.URLField(blank=True, null=True, verbose_name='配置路由')),
                ('user', models.ForeignKey(on_delete='配置者', related_name='setting_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'settings',
            },
        ),
    ]
