# Generated by Django 2.2.14 on 2021-03-24 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_organizations_isgroup'),
        ('accounts', '0009_auto_20201230_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ammic_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ammic_organization', to='rbac.Organizations'),
        ),
    ]
