# Generated by Django 2.2.14 on 2021-03-24 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_ammic_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ammic_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ammic_organization', to='rbac.Organizations'),
        ),
    ]
