# Generated by Django 2.2.14 on 2021-03-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210324_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ammic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ammic_group', to='rbac.Group'),
        ),
    ]
