# Generated by Django 2.2.14 on 2021-03-24 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210324_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterField(
            model_name='user',
            name='ammic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ammic_group', to='rbac.Group', verbose_name='开发组'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ammic_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ammic_organization', to='rbac.Organizations', verbose_name='组织架构'),
        ),
    ]
