# Generated by Django 2.2.14 on 2021-03-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='isgroup',
            field=models.BooleanField(default=True, verbose_name='是否是组'),
        ),
    ]
