# Generated by Django 2.2.14 on 2021-03-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_organizations_isgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizations',
            old_name='parentid',
            new_name='parent',
        ),
    ]
