# Generated by Django 2.2.14 on 2021-03-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20210324_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '开发组', 'verbose_name_plural': '开发组'},
        ),
    ]
