# Generated by Django 2.2.14 on 2021-03-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutfiles',
            old_name='user',
            new_name='applicant',
        ),
    ]
