# Generated by Django 2.2.14 on 2021-03-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0002_auto_20210325_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutfiles',
            name='fcomment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
