# Generated by Django 2.2.14 on 2021-03-25 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0003_auto_20210325_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutfiles',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
