# Generated by Django 2.2.14 on 2020-11-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaisons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liaisons',
            name='fhelper',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='协助者'),
        ),
    ]
