# Generated by Django 2.2.14 on 2020-11-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaisons', '0002_liaisons_fhelper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaisons',
            name='fupdtedt',
            field=models.DateField(auto_now=True, null=True, verbose_name='更新日期'),
        ),
    ]
