# Generated by Django 2.2.14 on 2020-11-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaisons', '0003_auto_20201110_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaisons',
            name='freleaserpt',
            field=models.FilePathField(blank=True, null=True, verbose_name='程序发布报告'),
        ),
    ]
