# Generated by Django 2.2.14 on 2020-11-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaisons', '0004_auto_20201111_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaisons',
            name='freleaserpt',
            field=models.FileField(blank=True, null=True, upload_to='liaison/%Y%m%d/', verbose_name='程序发布报告URL'),
        ),
    ]
