# Generated by Django 2.2.14 on 2020-11-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liaisons', '0005_auto_20201111_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaisons',
            name='fgroups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group', to='rbac.Group', verbose_name='组别'),
        ),
        migrations.AlterField(
            model_name='liaisons',
            name='fsirno',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SIR号'),
        ),
    ]
