# Generated by Django 2.2.14 on 2021-01-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaisons', '0006_auto_20201111_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaisons',
            name='fcreatedte',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='liaisons',
            name='fleader',
            field=models.CharField(max_length=60, verbose_name='负责人'),
        ),
    ]
