# Generated by Django 2.2.14 on 2021-01-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaisons', '0008_auto_20210128_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaisons',
            name='freleaserpt',
            field=models.URLField(blank=True, null=True, verbose_name='程序发布报告URL'),
        ),
    ]
