# Generated by Django 2.2.14 on 2021-01-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaisons', '0009_auto_20210128_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaisons',
            name='freleaserpt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='程序发布报告URL'),
        ),
    ]
