# Generated by Django 2.2.14 on 2021-01-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaisons', '0010_auto_20210128_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaisons',
            name='fleader',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='负责人'),
        ),
    ]
