# Generated by Django 2.2.14 on 2021-02-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaisons', '0011_auto_20210128_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liaisons',
            name='fassignedto',
            field=models.CharField(db_index=True, max_length=60, verbose_name='对应者'),
        ),
        migrations.AlterField(
            model_name='liaisons',
            name='fhelper',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, verbose_name='协助者'),
        ),
        migrations.AlterField(
            model_name='liaisons',
            name='fleader',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='liaisons',
            name='fodrno',
            field=models.CharField(db_index=True, max_length=20, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='liaisons',
            name='fslipno',
            field=models.CharField(db_index=True, max_length=20, verbose_name='联络票号'),
        ),
    ]
