# Generated by Django 2.2.14 on 2021-03-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liaisons', '0012_auto_20210204_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liaisons',
            name='fgroups',
        ),
        migrations.AddField(
            model_name='liaisons',
            name='forganization',
            field=models.IntegerField(blank=True, null=True, verbose_name='组织构架中组名'),
        ),
    ]
