# Generated by Django 2.2.14 on 2021-01-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesignReview',
        ),
        migrations.AlterModelOptions(
            name='codereview',
            options={'verbose_name': '设计or代码Review', 'verbose_name_plural': '设计or代码Review'},
        ),
    ]
