# Generated by Django 2.2.14 on 2020-11-10 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fprojectcd', models.CharField(max_length=20, verbose_name='项目代码')),
                ('fprojectnm', models.CharField(max_length=50, verbose_name='项目名称')),
                ('fprojectsn', models.CharField(max_length=10, verbose_name='项目')),
                ('fautoflg', models.CharField(max_length=1, verbose_name='自动生成联络票号')),
                ('fentdt', models.DateField(auto_now_add=True, verbose_name='登入日期')),
                ('fentusr', models.CharField(blank=True, max_length=24, null=True, verbose_name='登录者')),
                ('fupdtedt', models.DateField(blank=True, null=True, verbose_name='更新日期')),
                ('fupdteusr', models.CharField(blank=True, max_length=24, null=True, verbose_name='更新者')),
                ('fupdteprg', models.CharField(blank=True, max_length=110, null=True, verbose_name='更新程序名')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rbac.Group')),
            ],
            options={
                'verbose_name': '系统代码',
                'verbose_name_plural': '系统代码',
                'db_table': 'projectm',
            },
        ),
    ]
