# Generated by Django 2.2.14 on 2021-03-24 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20210324_1716'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='group',
        ),
        migrations.AddField(
            model_name='projects',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_organization', to='rbac.Organizations', verbose_name='组织构架中组名'),
        ),
    ]
