# Generated by Django 2.2.14 on 2021-03-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210324_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目代码', 'verbose_name_plural': '项目代码'},
        ),
    ]
