# Generated by Django 2.2.14 on 2020-11-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qadetail',
            old_name='fqahfid',
            new_name='qahf',
        ),
        migrations.AlterField(
            model_name='qahead',
            name='fupdtedt',
            field=models.DateField(auto_now=True, null=True, verbose_name='更新日期'),
        ),
    ]
