# Generated by Django 2.2.14 on 2020-12-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20201111_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadetail',
            name='fregression',
            field=models.CharField(default='N', max_length=1, verbose_name='回归测试'),
        ),
        migrations.AlterField(
            model_name='qadetail',
            name='fupdtedt',
            field=models.DateField(auto_now=True, null=True, verbose_name='更新日期'),
        ),
    ]
