# Generated by Django 2.2.14 on 2021-01-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20201230_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qahead',
            name='fcreatedte',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
    ]
