# Generated by Django 2.2.14 on 2021-01-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20210115_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='qadetail',
            name='fsortrule',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='排序规则'),
        ),
    ]
