# Generated by Django 2.2.14 on 2021-01-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0005_qadetail_fsortrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadetail',
            name='fsortrule',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='排序规则'),
        ),
    ]
