# Generated by Django 2.2.14 on 2021-01-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_auto_20210115_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='qadetail',
            name='fapprovallot',
            field=models.IntegerField(default=0, verbose_name='审核批次'),
        ),
        migrations.AddField(
            model_name='qahead',
            name='flastapprovallot',
            field=models.IntegerField(default=0, verbose_name='最后审核批次'),
        ),
    ]
